### ISSUE TITLE
Use `require('node:buffer')` rather than `Buffer` from global scope

### ISSUE THREAD

**Issue by benmccann** [ldthomas/apg-js#16]
Node.js recommends importing `Buffer` from `node:buffer`:
- https://nodejs.org/api/buffer.html#buffer
- https://nodejs.org/api/buffer.html#nodebuffer-module-apis

Using the `Buffer` from the global scope is causing issues for some users. E.g. https://github.com/spruceid/siwe/issues/168 and https://github.com/sveltejs/kit/pull/10214#issuecomment-1608991806

**Comment by ldthomas** [comment]
`apg-js` version 4.2.0 addresses this issue.
