### ISSUE TITLE
Improve error logging

### ISSUE THREAD

**Issue by ralfhandl** [ldthomas/apg-js#3]
Currently the command-line tool `apg.sh` first outputs errors in the input grammar, then lists the complete input, which can be rather long.

It took me a while to realize that the tool gives more hints on the errors than just
~~~
EXCEPTION THROWN: Error: apg.js: grammar has syntax errors
~~~
because the detailed error message was scrolled out of sight 😄 

It would improve use on the command-line if the error details would be written _after_ the input grammar.

This change is proposed in #4

**Comment by ldthomas** [comment]
sax.js looks good and as you say very popular. I'll probably finish adding the XML parser to apg-js anyway. There's always room for one more. And, hey, I'm retired with nothing better do to. :) Plus it's a fun project and not too hard after having already done it once in C. Cheers.

**Comment by ralfhandl** [comment]
Glad I didn't discourage you 😃
